### ISSUE TITLE
Migrate website to HTTPS

### ISSUE THREAD

**Issue by GaurangTandon** [IIIT-ECell/website#2]
Grab a free HTTPS certificate, please.
Chrome now marks HTTP pages as "Not secure".
[Even static websites **need** HTTPS.](https://www.troyhunt.com/heres-why-your-static-website-needs-https/)

**Comment by zubairabid** [comment]
@GaurangTandon

**Comment by GaurangTandon** [comment]
Actually you're right that it does not automatically redirect to https:// from http://.

However, most users won't add the protocol before the URL. If you tell them the URL is ecell.iiit.ac.in they will assume that the https:// will automatically be added if they just type ecell.iiit.ac.in in their omnibox.

**Comment by zubairabid** [comment]
@GaurangTandon Yeah we need to set up a redirect on the server.
I'll  be looking at it, after I fix some issue with the CA in general

**Comment by GaurangTandon** [comment]
Has this been fixed? I am no longer able to access http://ecell.iiit.ac.in

**Comment by YoogottamK** [comment]
Closing
